### ISSUE TITLE
windows 10 mobile support

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/SwiftBrowser#42]
to be updated

**Comment by Jaiganeshkumaran** [comment]
It doesn't work because your app requires build 16299 which was not released to mobile. Although the latest build of Windows 10 Mobile claims to be Version 1709, it's not the same build as other Windows devices. Instead, Microsoft decided to release a preview build to the public as 1709 for mobile. If you check the build number it would say 10.0.15254 instead of 10.0.16299 which is the real Fall Creators Update. Setting the minimum version to 1703 should make it work.

**Comment by FireCubeStudios** [comment]
targeting 1703 doesnt work because that version doesnt support .netstandard 2.0 (on pc) so now i get bunch of errors. if there was a way to support 15254 without going down to 15063 then it can work.

**Comment by Jaiganeshkumaran** [comment]
@FireCubeStudios Try to manually set the minimum version by editing the project file and the appx manifest. If that doesn't work try to download an insider SDK for Build 15254. Also, why do need .NET standard 2.0 since your app is Windows 10 only?

**Comment by FireCubeStudios** [comment]
.net standard is for the nuget packages i use. but i will try your suggestion and report back

**Comment by Jaiganeshkumaran** [comment]
If those packages offer a older version that doesn’t depend on .NET standard 2.0 try to downgrade to them or reimplement features that are provided by those libraries.

**Comment by FireCubeStudios** [comment]
i did everything but now i got this final error
![image](https://user-images.githubusercontent.com/40955345/88721052-1f298a80-d126-11ea-83aa-c5edc2a6e1c6.png)

**Comment by Jaiganeshkumaran** [comment]
The SDK doesn’t support the build unfortuanility. If there are versions to packages that support 1703 try to install them. If you can’t do that here’s an idea. Windows 10 natively supports app extensions. You can target your main app for 1703 and put everything that’s not compatible in an extension package and then check if it exists.

**Comment by FireCubeStudios** [comment]
im closing this issue now because mobile has very few users and i dont want to be stuck behind in old technologies. if i move form webview to webview 2 then mobile wont be supported anyway
