### ISSUE TITLE
webview memory not freed

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/SwiftBrowser#7]
webview memory is not freed when tab is closed. When a tab is closed I do a dispose method to remove all event handlers, remove webview from visual tree and set it to null but garbage collector doesnt collect it.

**Comment by Jaiganeshkumaran** [comment]
Do you accept contributions?

**Comment by FireCubeStudios** [comment]
yes i do however the github repo is outdated by a months worth of updates so im going to fix that today

**Comment by Jaiganeshkumaran** [comment]
Could you assign me to this issue?

**Comment by Jaiganeshkumaran** [comment]
Since EdgeHTML is written in C++, GC will not clean it up. Also, the WebView object is just a wrapper around the rendering engine. WebView doesn't provide a way to clean up the memory as it can be used again by another app. It gets cleaned up eventually but if you want to clean up instantly you could navigate to 'about:blank' multiple times. Note that the content in a web view is rendered by an external process but the web view itself is rendered by your process.

**Comment by FireCubeStudios** [comment]
interesting i will try that thanks for sharing!

**Comment by FireCubeStudios** [comment]
hmm seems like navigating to about blank multiple times didnt fix it. if webview is in c++ there could hav ebeen a method to free it but i dont know c++

**Comment by Jaiganeshkumaran** [comment]
> hmm seems like navigating to about blank multiple times didnt fix it. if webview is in c++ there could hav ebeen a method to free it but i dont know c++

Atleast try it 10 times and check the usage in Swift Browser's task manager. WebView is pretty smart and it will automatically remove unused content when more memory is needed. It doesn't provide a dispose method to free and I don't know why.

**Comment by FireCubeStudios** [comment]
ok i will try it

**Comment by FireCubeStudios** [comment]
thanks for sharing i will try it out using the code from the link

**Comment by FireCubeStudios** [comment]
it works the memory is freed but some 50 mb still remains but its a vast improvement. memory went from 50mb to 700mb and then shrank to 100mb. im closing the issue now as it seems to be fixed. thank you for your help i will credit you.
